# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Content.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Content(object):
    def setupUi(self, Content):
        Content.setObjectName("Content")
        Content.resize(1062, 815)
        self.centralwidget = QtWidgets.QWidget(Content)
        self.centralwidget.setObjectName("centralwidget")
        self.F1 = QtWidgets.QLabel(self.centralwidget)
        self.F1.setGeometry(QtCore.QRect(30, 20, 320, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.F1.sizePolicy().hasHeightForWidth())
        self.F1.setSizePolicy(sizePolicy)
        self.F1.setMaximumSize(QtCore.QSize(320, 201))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.F1.setFont(font)
        self.F1.setFrameShape(QtWidgets.QFrame.VLine)
        self.F1.setText("")
        self.F1.setTextFormat(QtCore.Qt.AutoText)
        self.F1.setPixmap(QtGui.QPixmap(":/newPrefix/C:/Users/Phaml/Pictures/Snap Camera Photo 3.jpg"))
        self.F1.setAlignment(QtCore.Qt.AlignCenter)
        self.F1.setWordWrap(False)
        self.F1.setIndent(0)
        self.F1.setOpenExternalLinks(True)
        self.F1.setObjectName("F1")
        Content.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Content)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 21))
        self.menubar.setObjectName("menubar")
        self.menuMEN = QtWidgets.QMenu(self.menubar)
        self.menuMEN.setObjectName("menuMEN")
        self.menuAA = QtWidgets.QMenu(self.menubar)
        self.menuAA.setObjectName("menuAA")
        self.menuContact = QtWidgets.QMenu(self.menubar)
        self.menuContact.setObjectName("menuContact")
        Content.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Content)
        self.statusbar.setObjectName("statusbar")
        Content.setStatusBar(self.statusbar)
        self.menuAA.addSeparator()
        self.menubar.addAction(self.menuMEN.menuAction())
        self.menubar.addAction(self.menuAA.menuAction())
        self.menubar.addAction(self.menuContact.menuAction())

        self.retranslateUi(Content)
        QtCore.QMetaObject.connectSlotsByName(Content)

    def retranslateUi(self, Content):
        _translate = QtCore.QCoreApplication.translate
        Content.setWindowTitle(_translate("Content", "MainWindow"))
        self.menuMEN.setTitle(_translate("Content", "About This App"))
        self.menuAA.setTitle(_translate("Content", "Author"))
        self.menuContact.setTitle(_translate("Content", "Contact"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Content = QtWidgets.QMainWindow()
    ui = Ui_Content()
    ui.setupUi(Content)
    Content.show()
    sys.exit(app.exec_())
