# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QMessageBox
import os
from Database import DataUserToken
from Main import Ui_MainWindow
from Course import Ui_Course
from loading import Loading
from remember import LocaL

opens = True


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(320, 315)
        Login.setMaximumSize(QtCore.QSize(320, 406))
        font = QtGui.QFont()
        font.setKerning(True)
        Login.setFont(font)
        Login.setAutoFillBackground(False)
        Login.setStyleSheet("background-color: rgb(255, 182, 193);")
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 0, 191, 61))
        self.label.setMaximumSize(QtCore.QSize(191, 16777215))
        font = QtGui.QFont()
        font.setFamily("VL Selphia")
        font.setPointSize(29)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.usernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameInput.setEnabled(True)
        self.usernameInput.setGeometry(QtCore.QRect(30, 80, 261, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameInput.sizePolicy().hasHeightForWidth())
        self.usernameInput.setSizePolicy(sizePolicy)
        self.usernameInput.setAutoFillBackground(False)
        self.usernameInput.setStyleSheet("font: 14pt \"VL Selphia\";\n"
                                         "color: rgb(255, 182, 193);\n"
                                         "background-color: rgb(255, 255, 255);\n"
                                         "border:none;")
        self.usernameInput.setText("")
        self.usernameInput.setObjectName("usernameInput")
        self.passwordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordInput.setGeometry(QtCore.QRect(30, 140, 261, 31))
        self.passwordInput.setStyleSheet("font: 14pt \"VL Selphia\";\n"
                                         "color: rgb(255, 182, 193);\n"
                                         "background-color: rgb(255, 255, 255);\n"
                                         "border:none\n"
                                         "")
        self.passwordInput.setText("")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.loginBtn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.openVideo())
        self.loginBtn.setEnabled(True)
        self.loginBtn.setGeometry(QtCore.QRect(80, 200, 161, 41))
        font = QtGui.QFont()
        font.setFamily("VL Selphia")
        font.setPointSize(13)
        self.loginBtn.setFont(font)
        self.loginBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.loginBtn.setAcceptDrops(False)
        self.loginBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loginBtn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "color: rgb(255, 182, 193);\n"
                                    "")
        self.loginBtn.setCheckable(False)
        self.loginBtn.setAutoDefault(False)
        self.loginBtn.setDefault(False)
        self.loginBtn.setFlat(False)
        self.loginBtn.setObjectName("loginBtn")
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 21))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)

        QtCore.QMetaObject.connectSlotsByName(Login)
        # self.openMainUsingToken()

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Đăng nhập"))
        Login.setWindowIcon(QIcon("favicon.png"))
        self.label.setText(_translate("Login", "CarrotDay"))
        self.usernameInput.setPlaceholderText(_translate("Login", "Username"))
        self.passwordInput.setPlaceholderText(_translate("Login", "Password"))
        self.loginBtn.setText(_translate("Login", "Đăng nhập nào !"))

    def openMainUsingToken(self):
        remember = LocaL().checkToken()
        if remember["code"] == 200:
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.window, Login, load, remember["token"])
            self.window.show()
            return True

    def openVideo(self):
        self.loginBtn.setText("Waiting...")
        user = DataUserToken(self.usernameInput.text(), self.passwordInput.text())
        self.loginBtn.setText("Đăng nhập nào !!")
        result = user.result
        if result["code"] == 404:
            self.showDialog("Sai thông tin đăng nhập")
        else:
            saving = LocaL().setToken(result["token"])
            self.window = QtWidgets.QMainWindow()
            load.loadbox.show()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.window, Login, load, result["token"])
            self.window.show()

    def showDialog(self, content):
        msgBox = QMessageBox()
        msgBox.setWindowIcon(QIcon("favicon.png"))
        msgBox.setText(content)
        msgBox.setWindowTitle("Lỗi")
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.exec()
        self.loginBtn.setText("Đăng nhập nào !!")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    load = Loading()
    load.loadbox.show()
    ui = Ui_Login()
    ui.setupUi(Login)
    if not ui.openMainUsingToken():
        Login.show()
        load.loadbox.hide()
    sys.exit(app.exec_())
