# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Content.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage
from Database import User
from Course import Ui_Course


class Ui_MainWindow(object):
    def openCourseWindow(self,MainWindow):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Course()
        self.ui.setupUi(self.window, MainWindow)
        self.window.show()

    def backToLogin(self, MainWindow, LoginWindow):
        MainWindow.hide()
        LoginWindow.show()

    def setupUi(self, MainWindow, LoginWindow, token="jzhzgxRG2zmCJAsMATSwd1Al6"):
        LoginWindow.hide()
        self.token = token
        self.user = User(token).result
        if (self.user["code"] == 404):
            self.backToLogin(MainWindow, LoginWindow)
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1000, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CourseArea = QtWidgets.QGroupBox(self.centralwidget)
        self.CourseArea.setGeometry(QtCore.QRect(0, 0, 1000, 400))
        self.CourseArea.setStyleSheet("background-color: rgb(255, 182, 193);")
        self.CourseArea.setTitle("")
        self.CourseArea.setObjectName("CourseArea")
        self.gridLayoutWidget = QtWidgets.QWidget(self.CourseArea)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(810, 20, 161, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.RegisterBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.RegisterBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.RegisterBtn.setStyleSheet("color: rgb(255, 182, 193);\n"
                                       "border:none;\n"
                                       "background-color: rgb(255, 255, 255);\n"
                                       "font: 14pt \"VL Selphia\";\n"
                                       "")
        self.RegisterBtn.setObjectName("RegisterBtn")
        self.gridLayout.addWidget(self.RegisterBtn, 2, 0, 1, 1)
        self.contactBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.contactBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.contactBtn.setStyleSheet("color: rgb(255, 182, 193);\n"
                                      "border:none;\n"
                                      "background-color: rgb(255, 255, 255);\n"
                                      "font: 14pt \"VL Selphia\";\n"
                                      "border-radius: 25pt;\n"
                                      "")
        self.contactBtn.setObjectName("contactBtn")
        self.gridLayout.addWidget(self.contactBtn, 0, 0, 1, 1)
        self.FeatureBtn0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.FeatureBtn0.setEnabled(False)
        self.FeatureBtn0.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.FeatureBtn0.setStyleSheet("color: rgb(255, 182, 193);\n"
                                       "border:none;\n"
                                       "background-color: rgb(255, 255, 255);\n"
                                       "font: 14pt \"VL Selphia\";\n"
                                       "")
        self.FeatureBtn0.setObjectName("FeatureBtn0")
        self.gridLayout.addWidget(self.FeatureBtn0, 5, 0, 1, 1)
        self.pairButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pairButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pairButton.setStyleSheet("color: rgb(255, 182, 193);\n"
                                      "border:none;\n"
                                      "background-color: rgb(255, 255, 255);\n"
                                      "font: 14pt \"VL Selphia\";\n"
                                      "")
        self.pairButton.setObjectName("pairButton")
        self.gridLayout.addWidget(self.pairButton, 3, 0, 1, 1)
        self.FeatureBtn1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.FeatureBtn1.setEnabled(False)
        self.FeatureBtn1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.FeatureBtn1.setStyleSheet("color: rgb(255, 182, 193);\n"
                                       "border:none;\n"
                                       "background-color: rgb(255, 255, 255);\n"
                                       "font: 14pt \"VL Selphia\";\n"
                                       "")
        self.FeatureBtn1.setObjectName("FeatureBtn1")
        self.gridLayout.addWidget(self.FeatureBtn1, 6, 0, 1, 1)
        self.DocBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.DocBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.DocBtn.setStyleSheet("color: rgb(255, 182, 193);\n"
                                  "border:none;\n"
                                  "background-color: rgb(255, 255, 255);\n"
                                  "font: 14pt \"VL Selphia\";\n"
                                  "")
        self.DocBtn.setObjectName("DocBtn")
        self.gridLayout.addWidget(self.DocBtn, 4, 0, 1, 1)
        self.AboutBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.AboutBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.AboutBtn.setStyleSheet("color: rgb(255, 182, 193);\n"
                                    "border:none;\n"
                                    "background-color: rgb(255, 255, 255);\n"
                                    "font: 14pt \"VL Selphia\";\n"
                                    "")
        self.AboutBtn.setObjectName("AboutBtn")
        self.gridLayout.addWidget(self.AboutBtn, 1, 0, 1, 1)
        self.FeatureBtn2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.FeatureBtn2.setEnabled(False)
        self.FeatureBtn2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.FeatureBtn2.setStyleSheet("color: rgb(255, 182, 193);\n"
                                       "border:none;\n"
                                       "background-color: rgb(255, 255, 255);\n"
                                       "font: 14pt \"VL Selphia\";\n"
                                       "")
        self.FeatureBtn2.setObjectName("FeatureBtn2")
        self.gridLayout.addWidget(self.FeatureBtn2, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.CourseArea)
        self.label.setGeometry(QtCore.QRect(30, 30, 771, 341))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/banner-khoahocnuoinick.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 400, 1000, 400))
        self.groupBox_2.setMinimumSize(QtCore.QSize(1000, 400))
        self.groupBox_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_2.setTabletTracking(False)
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 182, 193);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.avatar = QtWidgets.QLabel(self.groupBox_2)
        self.avatar.setGeometry(QtCore.QRect(20, 30, 191, 191))
        image = QImage()
        image.loadFromData(requests.get(self.user['avatar']).content)
        self.avatar.setPixmap(QtGui.QPixmap(image))
        self.avatar.setScaledContents(True)
        self.avatar.setObjectName("avatar")
        self.EmailLabel = QtWidgets.QLabel(self.groupBox_2)
        self.EmailLabel.setGeometry(QtCore.QRect(230, 30, 471, 31))
        font = QtGui.QFont()
        font.setFamily("VL Selphia")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.EmailLabel.setFont(font)
        self.EmailLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "font: 16pt \"VL Selphia\";")
        self.EmailLabel.setObjectName("EmailLabel")
        self.NameLabel = QtWidgets.QLabel(self.groupBox_2)
        self.NameLabel.setGeometry(QtCore.QRect(230, 60, 471, 31))
        font = QtGui.QFont()
        font.setFamily("VL Selphia")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.NameLabel.setFont(font)
        self.NameLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
                                     "font: 16pt \"VL Selphia\";")
        self.NameLabel.setObjectName("NameLabel")
        self.RoleLabel = QtWidgets.QLabel(self.groupBox_2)
        self.RoleLabel.setGeometry(QtCore.QRect(230, 90, 471, 31))
        font = QtGui.QFont()
        font.setFamily("VL Selphia")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.RoleLabel.setFont(font)
        self.RoleLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
                                     "font: 16pt \"VL Selphia\";")
        self.RoleLabel.setObjectName("RoleLabel")
        self.IDLabel = QtWidgets.QLabel(self.groupBox_2)
        self.IDLabel.setGeometry(QtCore.QRect(230, 120, 471, 31))
        font = QtGui.QFont()
        font.setFamily("VL Selphia")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.IDLabel.setFont(font)
        self.IDLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "font: 16pt \"VL Selphia\";")
        self.IDLabel.setObjectName("IDLabel")
        self.CourseLabel = QtWidgets.QLabel(self.groupBox_2)
        self.CourseLabel.setGeometry(QtCore.QRect(230, 150, 191, 31))
        font = QtGui.QFont()
        font.setFamily("VL Selphia")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.CourseLabel.setFont(font)
        self.CourseLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
                                       "font: 16pt \"VL Selphia\";")
        self.CourseLabel.setObjectName("CourseLabel")
        self.logout = QtWidgets.QPushButton(self.groupBox_2, clicked=lambda: self.backToLogin(MainWindow, LoginWindow))
        self.logout.setGeometry(QtCore.QRect(230, 190, 101, 31))
        self.logout.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.logout.setStyleSheet("color: rgb(255, 182, 193);\n"
                                  "border:none;\n"
                                  "background-color: rgb(255, 255, 255);\n"
                                  "font: 14pt \"VL Selphia\";\n"
                                  "")
        self.logout.setObjectName("logout")
        self.courseCombo = QtWidgets.QComboBox(self.groupBox_2)
        self.courseCombo.setGeometry(QtCore.QRect(410, 150, 301, 31))
        font = QtGui.QFont()
        font.setFamily("VL Selphia")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.courseCombo.setFont(font)
        self.courseCombo.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.courseCombo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                       "color: rgb(255, 182, 193);\n"
                                       "font: 12pt \"VL Selphia\";\n"
                                       "border:none;")
        self.courseCombo.setEditable(False)
        self.courseCombo.setObjectName("courseCombo")
        for category in self.user["category"]:
            self.courseCombo.addItem(category["name"])

        self.openCourse = QtWidgets.QPushButton(self.groupBox_2, clicked=lambda: self.openCourseWindow(MainWindow))
        self.openCourse.setGeometry(QtCore.QRect(730, 150, 201, 31))
        self.openCourse.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.openCourse.setStyleSheet("color: rgb(255, 182, 193);\n"
                                      "border:none;\n"
                                      "background-color: rgb(255, 255, 255);\n"
                                      "font: 14pt \"VL Selphia\";\n"
                                      "")
        self.openCourse.setObjectName("openCourse")
        self.logout_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.logout_2.setGeometry(QtCore.QRect(350, 190, 201, 31))
        self.logout_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.logout_2.setStyleSheet("color: rgb(255, 182, 193);\n"
                                    "border:none;\n"
                                    "background-color: rgb(255, 255, 255);\n"
                                    "font: 14pt \"VL Selphia\";\n"
                                    "")
        self.logout_2.setObjectName("logout_2")
        self.logout_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.logout_3.setGeometry(QtCore.QRect(570, 190, 141, 31))
        self.logout_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.logout_3.setStyleSheet("color: rgb(255, 182, 193);\n"
                                    "border:none;\n"
                                    "background-color: rgb(255, 255, 255);\n"
                                    "font: 14pt \"VL Selphia\";\n"
                                    "")
        self.logout_3.setObjectName("logout_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuUpdate = QtWidgets.QMenu(self.menubar)
        self.menuUpdate.setObjectName("menuUpdate")
        self.menuLogout = QtWidgets.QMenu(self.menubar)
        self.menuLogout.setObjectName("menuLogout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuUpdate.menuAction())
        self.menubar.addAction(self.menuLogout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Xin chào ," + self.user["name"]))
        self.RegisterBtn.setText(_translate("MainWindow", "Đăng ký khoá học"))
        self.contactBtn.setText(_translate("MainWindow", "Liên Hệ"))
        self.FeatureBtn0.setText(_translate("MainWindow", "Comming Soon"))
        self.pairButton.setText(_translate("MainWindow", "Đóng học phí"))
        self.FeatureBtn1.setText(_translate("MainWindow", "Coming Soon"))
        self.DocBtn.setText(_translate("MainWindow", "Tài liệu "))
        self.AboutBtn.setText(_translate("MainWindow", "Thông tin"))
        self.FeatureBtn2.setText(_translate("MainWindow", "Coming Soon"))
        self.EmailLabel.setText(_translate("MainWindow", "Email :" + self.user["email"]))
        self.NameLabel.setText(_translate("MainWindow", "Họ và tên :" + self.user["name"]))
        self.RoleLabel.setText(
            _translate("MainWindow", "Phân quyền : Người dùng" if self.user["role"] == 1 else "Phân quyền :Admin"))
        self.IDLabel.setText(_translate("MainWindow", "ID:" + self.token))
        self.CourseLabel.setText(_translate("MainWindow", "Khoá đang theo học"))
        self.logout.setText(_translate("MainWindow", "Đăng xuất"))
        # self.courseCombo.setItemText(0, _translate("MainWindow", "Khoá học làm  \"Dầu\""))
        # self.courseCombo.setItemText(1, _translate("MainWindow", "Khoá học cho người dz"))
        # self.courseCombo.setItemText(2, _translate("MainWindow", "Khoá học cho người dssss"))
        self.openCourse.setText(_translate("MainWindow", "Xem video bản ghi"))
        self.logout_2.setText(_translate("MainWindow", "Đổi thông tin cá nhân"))
        self.logout_3.setText(_translate("MainWindow", "Đổi mật khẩu"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuUpdate.setTitle(_translate("MainWindow", "Update"))
        self.menuLogout.setTitle(_translate("MainWindow", "Logout"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
