# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserArea(object):
    def setupUi(self, UserArea):
        UserArea.setObjectName("UserArea")
        UserArea.resize(1001, 684)
        self.CourseArea = QtWidgets.QGroupBox(UserArea)
        self.CourseArea.setGeometry(QtCore.QRect(9, 9, 985, 401))
        self.CourseArea.setStyleSheet("background-color: rgb(255, 182, 193);")
        self.CourseArea.setTitle("")
        self.CourseArea.setObjectName("CourseArea")
        self.gridLayoutWidget = QtWidgets.QWidget(self.CourseArea)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(819, 19, 159, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_4.setStyleSheet("color: rgb(255, 182, 193);\n"
                                        "border:none;\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "font: 14pt \"VL Selphia\";\n"
                                        "")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_2.setStyleSheet("color: rgb(255, 182, 193);\n"
                                        "border:none;\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "font: 14pt \"VL Selphia\";\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_7.setStyleSheet("color: rgb(255, 182, 193);\n"
                                        "border:none;\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "font: 14pt \"VL Selphia\";\n"
                                        "")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 5, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_5.setStyleSheet("color: rgb(255, 182, 193);\n"
                                        "border:none;\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "font: 14pt \"VL Selphia\";\n"
                                        "")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 3, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_8.setStyleSheet("color: rgb(255, 182, 193);\n"
                                        "border:none;\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "font: 14pt \"VL Selphia\";\n"
                                        "")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 6, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_6.setStyleSheet("color: rgb(255, 182, 193);\n"
                                        "border:none;\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "font: 14pt \"VL Selphia\";\n"
                                        "")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 4, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_3.setStyleSheet("color: rgb(255, 182, 193);\n"
                                        "border:none;\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "font: 14pt \"VL Selphia\";\n"
                                        "")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_9.setStyleSheet("color: rgb(255, 182, 193);\n"
                                        "border:none;\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "font: 14pt \"VL Selphia\";\n"
                                        "")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.CourseArea)
        self.label.setGeometry(QtCore.QRect(30, 30, 771, 341))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/banner-khoahocnuoinick.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(UserArea)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 420, 981, 251))
        self.groupBox_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_2.setTabletTracking(False)
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 182, 193);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.avatar = QtWidgets.QLabel(self.groupBox_2)
        self.avatar.setGeometry(QtCore.QRect(20, 30, 191, 191))
        self.avatar.setStyleSheet("background:red")
        self.avatar.setText("")
        self.avatar.setPixmap(QtGui.QPixmap("C:/Users/Phaml/Desktop/unnamed.jpg"))
        self.avatar.setScaledContents(True)
        self.avatar.setObjectName("avatar")
        self.EmailLabel = QtWidgets.QLabel(self.groupBox_2)
        self.EmailLabel.setGeometry(QtCore.QRect(230, 30, 471, 31))
        font = QtGui.QFont()
        font.setFamily("VL Selphia")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.EmailLabel.setFont(font)
        self.EmailLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "font: 16pt \"VL Selphia\";")
        self.EmailLabel.setObjectName("EmailLabel")
        self.NameLabel = QtWidgets.QLabel(self.groupBox_2)
        self.NameLabel.setGeometry(QtCore.QRect(230, 60, 471, 31))
        font = QtGui.QFont()
        font.setFamily("VL Selphia")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.NameLabel.setFont(font)
        self.NameLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
                                     "font: 16pt \"VL Selphia\";")
        self.NameLabel.setObjectName("NameLabel")
        self.RoleLabel = QtWidgets.QLabel(self.groupBox_2)
        self.RoleLabel.setGeometry(QtCore.QRect(230, 90, 471, 31))
        font = QtGui.QFont()
        font.setFamily("VL Selphia")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.RoleLabel.setFont(font)
        self.RoleLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
                                     "font: 16pt \"VL Selphia\";")
        self.RoleLabel.setObjectName("RoleLabel")
        self.IDLabel = QtWidgets.QLabel(self.groupBox_2)
        self.IDLabel.setGeometry(QtCore.QRect(230, 120, 471, 31))
        font = QtGui.QFont()
        font.setFamily("VL Selphia")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.IDLabel.setFont(font)
        self.IDLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "font: 16pt \"VL Selphia\";")
        self.IDLabel.setObjectName("IDLabel")
        self.CourseLabel = QtWidgets.QLabel(self.groupBox_2)
        self.CourseLabel.setGeometry(QtCore.QRect(230, 150, 191, 31))
        font = QtGui.QFont()
        font.setFamily("VL Selphia")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.CourseLabel.setFont(font)
        self.CourseLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
                                       "font: 16pt \"VL Selphia\";")
        self.CourseLabel.setObjectName("CourseLabel")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(230, 190, 101, 31))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton.setStyleSheet("color: rgb(255, 182, 193);\n"
                                      "border:none;\n"
                                      "background-color: rgb(255, 255, 255);\n"
                                      "font: 14pt \"VL Selphia\";\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(410, 150, 301, 31))
        font = QtGui.QFont()
        font.setFamily("VL Selphia")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "color: rgb(255, 182, 193);\n"
                                    "font: 12pt \"VL Selphia\";\n"
                                    "border:none;")
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.openCourse = QtWidgets.QPushButton(self.groupBox_2)
        self.openCourse.setGeometry(QtCore.QRect(730, 150, 201, 31))
        self.openCourse.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.openCourse.setStyleSheet("color: rgb(255, 182, 193);\n"
                                      "border:none;\n"
                                      "background-color: rgb(255, 255, 255);\n"
                                      "font: 14pt \"VL Selphia\";\n"
                                      "")
        self.openCourse.setObjectName("openCourse")

        self.retranslateUi(UserArea)
        QtCore.QMetaObject.connectSlotsByName(UserArea)

    def retranslateUi(self, UserArea):
        _translate = QtCore.QCoreApplication.translate
        UserArea.setWindowTitle(_translate("UserArea", "Form"))
        self.pushButton_4.setText(_translate("UserArea", "Đăng ký khoá học"))
        self.pushButton_2.setText(_translate("UserArea", "Liên Hệ"))
        self.pushButton_7.setText(_translate("UserArea", "Comming Soon"))
        self.pushButton_5.setText(_translate("UserArea", "Đóng học phí"))
        self.pushButton_8.setText(_translate("UserArea", "Coming Soon"))
        self.pushButton_6.setText(_translate("UserArea", "Tài liệu "))
        self.pushButton_3.setText(_translate("UserArea", "Thông tin"))
        self.pushButton_9.setText(_translate("UserArea", "Coming Soon"))
        self.EmailLabel.setText(_translate("UserArea", "Email : Phamquanglinhdev@gmail.com"))
        self.NameLabel.setText(_translate("UserArea", "Họ và tên : Phạm Quang Linh"))
        self.RoleLabel.setText(_translate("UserArea", "Phân Quyền : Admin"))
        self.IDLabel.setText(_translate("UserArea", "ID : 129188090098120"))
        self.CourseLabel.setText(_translate("UserArea", "Khoá đang theo học"))
        self.pushButton.setText(_translate("UserArea", "Đăng xuất"))
        self.comboBox.setItemText(0, _translate("UserArea", "Khoá học làm  \"Dầu\""))
        self.comboBox.setItemText(1, _translate("UserArea", "Khoá học cho người dz"))
        self.openCourse.setText(_translate("UserArea", "Xem video bản ghi"))

    def SetupFunc(self):
        print("hi")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    UserArea = QtWidgets.QWidget()
    ui = Ui_UserArea()
    ui.setupUi(UserArea)
    UserArea.show()
    sys.exit(app.exec_())
